const BOOKS_DIR_NAME = 'Books';
const AI_PACKS_DIR_NAME = 'AI Packs';
const BOOK_REGISTRY_FILE = 'book-registry.json';
const AI_PACK_REGISTRY_FILE = 'ai-pack-registry.json';
const BOOK_JSON_FILE = 'book.json';
const AI_PACK_MANIFEST_FILE = 'manifest.json';
const BOOK_ANNOTATIONS_FILE = 'student-annotations.json';
const BOOK_PACKAGE_EXTENSION = '.noprepbook';
const MAX_INLINE_IMAGE_BYTES = 25 * 1024 * 1024;
const MAX_AUDIO_RECORDING_BYTES = 100 * 1024 * 1024;
const MAX_STT_AUDIO_BYTES = 250 * 1024 * 1024;
const MAX_TTS_TEXT_CHARS = 5000;
const MAX_TOPIC_SNAPSHOT_BYTES = 100 * 1024 * 1024;
const MAX_ZIP_ENTRIES = 200000;
const ZIP_IFMT = 0o170000;
const ZIP_IFLNK = 0o120000;
const WARM_DIALOGUE_IDLE_MS = 10 * 60 * 1000;
const WARM_DIALOGUE_START_TIMEOUT_MS = 3 * 60 * 1000;
const WARM_DIALOGUE_TURN_TIMEOUT_MS = 5 * 60 * 1000;

module.exports = {
  BOOKS_DIR_NAME,
  AI_PACKS_DIR_NAME,
  BOOK_REGISTRY_FILE,
  AI_PACK_REGISTRY_FILE,
  BOOK_JSON_FILE,
  AI_PACK_MANIFEST_FILE,
  BOOK_ANNOTATIONS_FILE,
  BOOK_PACKAGE_EXTENSION,
  MAX_INLINE_IMAGE_BYTES,
  MAX_AUDIO_RECORDING_BYTES,
  MAX_STT_AUDIO_BYTES,
  MAX_TTS_TEXT_CHARS,
  MAX_TOPIC_SNAPSHOT_BYTES,
  MAX_ZIP_ENTRIES,
  ZIP_IFMT,
  ZIP_IFLNK,
  WARM_DIALOGUE_IDLE_MS,
  WARM_DIALOGUE_START_TIMEOUT_MS,
  WARM_DIALOGUE_TURN_TIMEOUT_MS
};
