/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function create_fingerprint(machine: string, host: string, platform: string): string
export declare function validate_license_signature(machineId: string, expiry: number, nonce: string, signature: string, expectedMachine: string): boolean
export declare function approve_feature_unlock(featureName: string, machineId: string, expiry: number, nonce: string, signature: string, expectedMachine: string): string | null
